### ISSUE TITLE
Add new placeholders on the wiki

### ISSUE THREAD

**Issue by andrei1058** [andrei1058/docs#68]
Someone please mention this update on the wiki:
https://github.com/andrei1058/BedWars1058/pull/796

**Comment by bijju089** [comment]
Sure

**Comment by OPADILOP** [comment]
> Someone please mention this update on the wiki: [andrei1058/BedWars1058#796](https://github.com/andrei1058/BedWars1058/pull/796)

what does the placeholder actually shows?

**Comment by OPADILOP** [comment]
#70 looks like this is the thing you wanted.
Check it and review it if there is any issues...
